# POST  http://localhost:5000/api/auth/authenticate
# Content-Type: application/json

# {
#     "Login": "Admin",
#     "Password": "admin"
# }

GET http://localhost:5000/api/room
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNTkyOTUyMTQwLCJleHAiOjE1OTI5NTI3NDAsImlhdCI6MTU5Mjk1MjE0MH0.0EaH-2N72bcFHc5OSd-R6J15HXymT7H0gwYUqYJT254

# POST  http://localhost:5000/api/card
# Content-Type: application/json

# {
#     "Name": "DayTest",
#     "Period": "1 мес",
#     "Price": 4500.00
# }

# GET http://localhost:5000/api/card
# Content-Type: application/json